// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkK_8TtqATHOcihXieMAt_RpppmSHZqUs',
    appId: '1:494673348369:web:dc6d931859206bd6feeeb0',
    messagingSenderId: '494673348369',
    projectId: 'projectv-cbc7a',
    authDomain: 'projectv-cbc7a.firebaseapp.com',
    storageBucket: 'projectv-cbc7a.appspot.com',
    measurementId: 'G-0J3GPSL2M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6DW3VHM7g8LRvnRU8NrlTOyDkjMBTTQ',
    appId: '1:494673348369:android:a4fbc4bdb88b7881feeeb0',
    messagingSenderId: '494673348369',
    projectId: 'projectv-cbc7a',
    storageBucket: 'projectv-cbc7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jM49Hbn8qHScx__ZsImR5LmooF5oBF8',
    appId: '1:494673348369:ios:59ff96dadeb025c3feeeb0',
    messagingSenderId: '494673348369',
    projectId: 'projectv-cbc7a',
    storageBucket: 'projectv-cbc7a.appspot.com',
    iosClientId: '494673348369-knc4prde7amhl1ll26t9s3ood6bnvsp9.apps.googleusercontent.com',
    iosBundleId: 'app.bloom.vivid',
  );
}
